version: '3'

volumes:
  postgres-data:
      driver: local
      
services:
#      Api layer
#  api:
#    image: microsoft/aspnetcore:2.0
#    build:
#      .
#    ports:
#      - 5000:5000
#    depends_on:
#        - postgres
#        
#        Our PostgreSQL service
  postgres:
    image: postgres:9.6.1
    ports:
      - 32769:32769
    volumes:
      - ./db/dumps:/db/dumps
      - ./tmp:/tmp
      - postgres-data:/var/lib/postgresql/data
    environment: